version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: mini-inbox-backend
    env_file:
      - ./backend/.env
    volumes:
      - ./data/processed:/app/data/processed
    ports:
      - "8000:8000"
    depends_on:
      - n8n

  frontend:
    build:
      context: ./frontend/stalse-mvp
      dockerfile: Dockerfile
    container_name: mini-inbox-frontend
    volumes:
      - ./frontend/stalse-mvp:/app
      - /app/node_modules # <--- ADD THIS LINE
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000

  n8n:
    image: n8nio/n8n:latest
    container_name: mini-inbox-n8n
    ports:
      - "5679:5678"  # host 5679, container 5678
    volumes:
      - ./n8n:/home/node/.n8n
    environment:
      - N8N_BASIC_AUTH_ACTIVE=false
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
